version: '3.1'
services:
  elasticsearch:
    image: elasticsearch:7.1.1
    environment:
      ES_JAVA_OPTS: "-Xms1g -Xmx1g"
    ports:
      - "9203:9200"
      - "9302:9300"
    volumes:
      - ./elasticsearch/config/:/etc/elasticsearch/config/
    networks: 
      - elk_env
  kibana:
    image: kibana:7.1.1
    ports:
      - 5601:5601
    volumes:
      - ./kibana/config/:/opt/kibana/config/
    networks:
      - elk_env
  logstash:
    image: logstash:7.1.1
    command: -f /etc/logstash/conf.d/
    ports:
      - 5000:5000
    volumes:
      - ./logstash/config:/etc/logstash/conf.d
    networks:
      - elk_env
networks:
  elk_env: